# Generated by Django 4.0.6 on 2022-08-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='picture')),
                ('heading', models.TextField(max_length=150)),
                ('desc', models.TextField()),
            ],
        ),
    ]
